CREATE TABLE public."Projetos" (
    "Id" UUID PRIMARY KEY,
    "Nome" VARCHAR(255) NOT NULL,
    "Descricao" TEXT NOT NULL,
    "Status" INTEGER NOT NULL,
    "DataInicio" TIMESTAMP NOT NULL,
    "DataTermino" TIMESTAMP,
    "Orcamento" DECIMAL NOT NULL,
    "FaseAtual" INTEGER NOT NULL,
    "GerenteTorre" VARCHAR(255) REFERENCES public."Membros"("NomeCompleto"),
    "DataCriacao" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DataAtualizacao" TIMESTAMP,
    "DataDelecao" TIMESTAMP,
    "Ativo" BOOLEAN NOT NULL,
    "DocumentoId" UUID[] NOT NULL,
    "TesteId" UUID[] NOT NULL,
    "HistoricoAlteracaoId" UUID[] NOT NULL,
    "LicencaId" UUID[] NOT NULL,
    "EquipeId" UUID[] NOT NULL,
    CONSTRAINT "FK_Documentos" FOREIGN KEY ("DocumentoId") REFERENCES public."Documentos"("Id"),
    CONSTRAINT "FK_Testes" FOREIGN KEY ("TesteId") REFERENCES public."Testes"("Id"),
    CONSTRAINT "FK_HistoricoAlteracoes" FOREIGN KEY ("HistoricoAlteracaoId") REFERENCES public."HistoricoAlteracoes"("Id"),   
    CONSTRAINT "FK_Licencas" FOREIGN KEY ("LicencaId") REFERENCES public."Licencas"("Id"),
    CONSTRAINT "FK_Equipes" FOREIGN KEY ("EquipeId") REFERENCES public."Equipes"("Id")
);